#+TITLE: OrgRoamPublish

This repo provides a GitHub action to allow you to publish org-roam files to
html files. I use this action to publish my org-roam notes to my website:
https://www.ethanp.dev/.

This repo is built off of the [[https://github.com/maker2413/OrgPublish][OrgPublish]] image I also made. This repo just adds
the library files required to install org-roam to the OrgPublish image and then
also installs the org-roam package. The publish.el files has also been updated
to incorporate org-roam to the publish function.

* Action Parameters
  This action has the following inputs that can be configured:
  - publish_script :: used to specify a custom elisp publish script.

* Usage
  #+begin_src yaml
    name: Publish
    on:
      push:
        branches:
          - master

    jobs:
      deploy:
        runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Deploy to cluster
          uses: maker2413/OrgRoamPublish@v1.0.0
  #+end_src

* Running Docker Image
  You can also run this docker image without utilizing the action. This can be
  useful for local publishing outside of GitHub actions or for developing a
  custom elisp script for publishing. To run this docker image to publish your
  org-roam files to html you just have to run the following command:

  ~docker run -v <org-roam directory>:/opt/OrgFiles maker2413/orgroampublish~

  You can also run your own custom publish script by simply providing it as an
  argument to this command:

  ~docker run -v <org-roam directory>:/opt/OrgFiles maker2413/orgroampublish <custom.el>~
